[workspace]
members = ["order-book-core", "order-book-cli", "demo"]
resolver = "2"

[workspace.dependencies]
rust_decimal = "1.37.2"
clap = { version = "4.5", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["display"] }