[package]
name = "order-book-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
order-book-core = { path = "../order-book-core", features = ["cli"] }
clap = { workspace = true }
shlex = "1.3"
rust_decimal = { workspace = true }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"